/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.capgemini.todoapp;

import controller.ProjectController;
import controller.TaskController;
import java.sql.SQLException;
import java.util.List;
import model.Project;
import java.util.Date;
import model.Task;


public class App {
    
    @SuppressWarnings("empty-statement")
    public static void main(String[] args) throws SQLException {
//TODO code application logic here

   
//     ProjectController projectController = new ProjectController(); 
//
//     Project project = new Project();
//     project.setId(6);
//     project.setName("Novo nome do projeto");
//     project.setDescription("description");
//    
//     projectController.update(project);
//
//     List<Project> projects = projectController.getAll();
//     System.out.println ("Total de projetos = " + projects.size());
//     
//     projectController.removeBYid(6);
//     
//       TaskController taskController = new TaskController();
//       
//       Task task = new Task();
//       task.setId(7);
//       task.setName("Criar tela da aplicação");
//       task.getDescription("Devem ser criadas telas para os cadastros");
//       task.getNotes("Sem notas");
//       task.isIsCompleted(false);
//       task.getDeadline(new Date());
//       
//       taskController.save(task);
//     
//       task.getName("Alterar telas de aplicação");
//       taskController.update(task);
//       List<Task> tasks = taskController.getAll(7);
//       System.out.println("Total de tarefas = " + tasks.size());
       
       
       
       
    
    }
}
